apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ktr9sootf-python 
  janus-idp.io/tekton: ktr9sootf-python
  backstage.io/kubernetes-id: ktr9sootf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ktr9sootf-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml